version: "3.8"

services:
  server:
    build: ./server
    container_name: gasoil-server
    ports:
      - "5000:5000"
    env_file:
      - .env

  client:
    build: ./client
    container_name: gasoil-client
    ports:
      - "3000:3000"
    depends_on:
      - server
