version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: always

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    restart: always

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    restart: always
